USE SUCOS_FRUTAS;

--SELECT * FROM TABELA_DE_CLIENTES;

--SELECT TOP 10 * FROM TABELA_DE_CLIENTES;

--SELECT 
--	ESTADO AS UF
--	,CPF
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES;

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,CPF
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES;

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,CPF
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC;


--SELECT 
--	TC.ESTADO AS [UNIDADE FEDERATIVA]
--	,TC.CPF
--	,TC.IDADE
--FROM 
--	TABELA_DE_CLIENTES TC;

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,CPF
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	LOWER(ESTADO) = 'SP';

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,CPF
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	IDADE <> 18;

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	NOME > 'G';

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	ESTADO = 'RJ' AND IDADE >= 18;

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	ESTADO = 'RJ' OR IDADE >= 18;

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	NOT ESTADO = 'RJ';

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	(ESTADO = 'RJ' AND IDADE >= 18) OR (IDADE < 18 AND ESTADO <> 'RJ');

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	ESTADO IN ('RJ','SP');

--SELECT 
--	ESTADO AS [UNIDADE FEDERATIVA]
--	,NOME
--	,IDADE
--FROM 
--	TABELA_DE_CLIENTES TC
--WHERE
--	IDADE BETWEEN 16 AND 30;

--SELECT TOP (1000) [CODIGO_DO_PRODUTO]
--      ,[NOME_DO_PRODUTO]
--      ,[EMBALAGEM]
--      ,[TAMANHO]
--      ,[SABOR]
--      ,[PRECO_DE_LISTA]
--  FROM [SUCOS_FRUTAS].[dbo].[TABELA_DE_PRODUTOS]
--  WHERE 
--	NOME_DO_PRODUTO LIKE '%A%'

--SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

--SELECT DISTINCT ESTADO FROM TABELA_DE_CLIENTES;

--SELECT MIN(IDADE) AS MENOR_IDADE FROM TABELA_DE_CLIENTES;

--SELECT MAX(IDADE) AS MAIOR_IDADE FROM TABELA_DE_CLIENTES;

--SELECT AVG(IDADE) AS MEDIA_IDADE FROM TABELA_DE_CLIENTES;

--SELECT SUM(IDADE) AS SOMA_IDADE FROM TABELA_DE_CLIENTES;

--SELECT 
--	*
--FROM
--	TABELA_DE_CLIENTES
--ORDER BY
--	VOLUME_DE_COMPRA DESC, LIMITE_DE_CREDITO DESC, IDADE DESC;

--SELECT
--	ESTADO,
--	AVG(VOLUME_DE_COMPRA)
--FROM
--	TABELA_DE_CLIENTES
--GROUP BY
--	ESTADO;

--SELECT
--	ESTADO,
--	AVG(VOLUME_DE_COMPRA) AS [VOLUME MÉDIO DE COMPRAS]
--FROM
--	TABELA_DE_CLIENTES
--WHERE
--	IDADE >= 25
--GROUP BY
--	ESTADO
--HAVING
--	AVG(VOLUME_DE_COMPRA) > 20000;

--SELECT
--	NOME,
--	IDADE,
--	(CASE
--		WHEN IDADE < 18 THEN 'CRIANÇA'
--		WHEN IDADE BETWEEN 18 AND 22 THEN 'ADULTO'
--		WHEN IDADE BETWEEN 23 AND 30 THEN 'MUITO ADULTO'
--		ELSE 'IDOSO'
--	END) AS [FAIXA ETÁRIA]
--FROM
--	TABELA_DE_CLIENTES

SELECT
	C.NOME AS CLIENTE
	,NF.NUMERO
	,V.NOME AS VENDEDOR
	,SUM(I.PRECO * I.QUANTIDADE) AS [VALOR(R$)]
FROM
	TABELA_DE_CLIENTES C
INNER JOIN
	NOTAS_FISCAIS NF
ON
	C.CPF = NF.CPF
INNER JOIN
	TABELA_DE_VENDEDORES V
ON
	V.MATRICULA = NF.MATRICULA
INNER JOIN
	ITENS_NOTAS_FISCAIS I
ON
	NF.NUMERO = I.NUMERO
GROUP BY
	C.NOME
	,NF.NUMERO
	,V.NOME