USE SUCOS_FRUTAS;

SELECT
	C.NOME,
	NF.NUMERO
FROM
	NOTAS_FISCAIS NF
FULL JOIN
	TABELA_DE_CLIENTES C
ON
	C.CPF = NF.CPF;

INSERT INTO TABELA_DE_CLIENTES (CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) VALUES 
('403596178', 'Lucas Gonzalez', 'R. Ari Barroso', '', 'Presidente Altino', 'Osasco', 'SP', '0000000', '1990-09-01', 27, 'M', 170000.0000, 24500, 0);

SELECT TOP 3
	I.CODIGO_DO_PRODUTO,
	P.NOME_DO_PRODUTO,
	SUM(I.QUANTIDADE) AS QUANTIDADE,
	SUM(I.QUANTIDADE*I.PRECO) AS FATURAMENTO
FROM
	ITENS_NOTAS_FISCAIS I
INNER JOIN
	TABELA_DE_PRODUTOS P
ON
	I.CODIGO_DO_PRODUTO = P.CODIGO_DO_PRODUTO
GROUP BY
	I.CODIGO_DO_PRODUTO,
	P.NOME_DO_PRODUTO
ORDER BY
	FATURAMENTO DESC;

SELECT
	DATA_VENDA,
	ROUND(SUM(I.QUANTIDADE*I.PRECO),2) AS FATURAMENTO
FROM
	NOTAS_FISCAIS NF
INNER JOIN
	ITENS_NOTAS_FISCAIS I
ON
	NF.NUMERO = I.NUMERO
GROUP BY
	DATA_VENDA
ORDER BY
	FATURAMENTO DESC;

SELECT DISTINCT
	BAIRRO
FROM
	TABELA_DE_CLIENTES
UNION
SELECT DISTINCT
	BAIRRO
FROM
	TABELA_DE_VENDEDORES;

SELECT 
	*
FROM
	TABELA_DE_CLIENTES
WHERE BAIRRO IN(
SELECT DISTINCT
	BAIRRO
FROM
	TABELA_DE_VENDEDORES
);

SELECT
	CONCAT(
			BAIRRO
			,' - '
			,CIDADE
			,' - '
			,ESTADO
			)
FROM
	TABELA_DE_CLIENTES;

SELECT 
	LEFT(NOME_DO_PRODUTO,15)
FROM
	TABELA_DE_PRODUTOS;

SELECT TOP 1
	REPLACE('987,55',',','.') AS FATURAMENTO
FROM
	ITENS_NOTAS_FISCAIS I;

SELECT
	GETDATE();

SELECT
	DATEADD(DAY,20,GETDATE());

SELECT
	DATEDIFF(HOUR,GETDATE(),'2023-12-31');
